export type ErrorRow = {
  id: string;
  mandarin: string;
  transfer: string;
  wrong: string;
  right: string;
  weeks: string;
  exam: string;
};

export const ERROR_MATRIX: ErrorRow[] = [
  {
    id: "articles",
    mandarin: "中文名词前没有 a / an / the",
    transfer: "漏冠词，或把 the 乱加在第一次出现的名词前",
    wrong: "I lost water bottle.",
    right: "I lost a water bottle.",
    weeks: "A2-0",
    exam: "A2 Key R4/R5 cloze",
  },
  {
    id: "zero-article-by",
    mandarin: "「坐公交」像一个名词短语",
    transfer: "交通方式误加 the",
    wrong: "I go to school by the bus.",
    right: "I go to school by bus.",
    weeks: "A2-0 · A2-11",
    exam: "A2 Key R5 · AEIS vocab",
  },
  {
    id: "3sg",
    mandarin: "动词不随人称变化",
    transfer: "第三人称现在时漏 -s",
    wrong: "She wake up at 6:15.",
    right: "She wakes up at 6:15.",
    weeks: "A2-1",
    exam: "A2 Key R4 · AEIS SVA",
  },
  {
    id: "sva-everyone",
    mandarin: "「大家」像复数",
    transfer: "everyone / the team of… 后用复数动词",
    wrong: "Everyone have a tray.",
    right: "Everyone has a tray.",
    weeks: "SEC-1",
    exam: "AEIS 50-MCQ SVA",
  },
  {
    id: "tense-shift",
    mandarin: "时态靠时间词，不靠动词形态",
    transfer: "叙事中现在时、过去时混用",
    wrong: "Yesterday I go to the canteen and buy chicken rice.",
    right: "Yesterday I went to the canteen and bought chicken rice.",
    weeks: "A2-3 · SEC-0",
    exam: "A2 Key W · AEIS composition",
  },
  {
    id: "present-perfect",
    mandarin: "「了」既像过去也像完成",
    transfer: "有 yesterday 却用 have gone；有 for six months 却用 went",
    wrong: "I have went there last year.",
    right: "I came last year. / I have been here for six months.",
    weeks: "B1-0 · SEC-8",
    exam: "B1 R5/R6 · AEIS tense MCQ",
  },
  {
    id: "continuous",
    mandarin: "「正在」用副词，不用 be + -ing",
    transfer: "I painting now",
    wrong: "I painting now.",
    right: "I am painting now.",
    weeks: "A2-2",
    exam: "A2 Key R4",
  },
  {
    id: "quantifiers",
    mandarin: "量词系统不同，不可数也会「一个」",
    transfer: "two breads / a homework / how many rice",
    wrong: "I have a homework.",
    right: "I have some homework. / I have a piece of homework.",
    weeks: "A2-4 · SEC-3",
    exam: "A2 Key R5 · AEIS cloze",
  },
  {
    id: "comparatives",
    mandarin: "「更」是副词，不变形容词",
    transfer: "more bigger / he is tall than me",
    wrong: "Priya is more faster than me.",
    right: "Priya is faster than I am. / Priya is faster than me.",
    weeks: "A2-5 · B1-1",
    exam: "A2/B1 grammar cloze",
  },
  {
    id: "prep-time",
    mandarin: "时间前只用「在」",
    transfer: "in Monday / on 7 o'clock / in morning",
    wrong: "English is in Monday at the morning.",
    right: "English is on Monday in the morning.",
    weeks: "A2-6 · SEC-2",
    exam: "A2 Key R5 · AEIS prepositions",
  },
  {
    id: "prep-place",
    mandarin: "「在」不区分 in / on / at",
    transfer: "in the bus / on the classroom",
    wrong: "We meet in the school gate.",
    right: "We meet at the school gate.",
    weeks: "A2-11",
    exam: "A2 Key R5",
  },
  {
    id: "like-ing",
    mandarin: "喜欢 + 动词原形",
    transfer: "I like swim / I enjoy to read",
    wrong: "I enjoy to read in the library.",
    right: "I enjoy reading in the library.",
    weeks: "A2-9",
    exam: "A2 Key R4",
  },
  {
    id: "modals",
    mandarin: "必须 / 可以 后面常加「去」",
    transfer: "must to / can to",
    wrong: "You must to queue.",
    right: "You must queue.",
    weeks: "A2-8 · SEC-4",
    exam: "AEIS grammar MCQ",
  },
  {
    id: "although-but",
    mandarin: "虽然…但是…成对出现",
    transfer: "Although…, but…",
    wrong: "Although I was nervous, but I tried.",
    right: "Although I was nervous, I tried.",
    weeks: "B1-7 · SEC-0 · SEC-9",
    exam: "AEIS sentence / cloze",
  },
  {
    id: "because-so",
    mandarin: "因为…所以…成对",
    transfer: "Because…, so…",
    wrong: "Because it rained, so Sports Day stopped.",
    right: "Because it rained, Sports Day stopped. / It rained, so Sports Day stopped.",
    weeks: "SEC-6",
    exam: "AEIS linkers",
  },
  {
    id: "if-when",
    mandarin: "如果 / 当 在口语里不分",
    transfer: "if 用于必然发生的事",
    wrong: "If the bell rings, we stand. (every day, certain)",
    right: "When the bell rings, we stand.",
    weeks: "SEC-7",
    exam: "AEIS conjunctions",
  },
  {
    id: "too-enough",
    mandarin: "太 / 够 位置相同",
    transfer: "enough 放错：enough tall",
    wrong: "He is enough tall to reach the shelf.",
    right: "He is tall enough to reach the shelf.",
    weeks: "B1-9 · SEC-10",
    exam: "B1 Key word transform · AEIS",
  },
  {
    id: "relative",
    mandarin: "定语从句无关系词",
    transfer: "The girl sits next to me is Priya.",
    wrong: "The book who I read was long.",
    right: "The book which/that I read was long.",
    weeks: "B1-5",
    exam: "B1 R6",
  },
  {
    id: "reported",
    mandarin: "转述不改时态、不改指示词",
    transfer: "She said she is tired yesterday.",
    wrong: "Ms Tan said the test is tomorrow. (said yesterday)",
    right: "Ms Tan said the test was the next day.",
    weeks: "B1-4",
    exam: "B1 R6 / writing",
  },
  {
    id: "collocation",
    mandarin: "直译中文搭配",
    transfer: "open the light / eat medicine / look book",
    wrong: "Please open the light.",
    right: "Please turn on the light.",
    weeks: "all · vocab modules",
    exam: "AEIS vocab · B1 cloze",
  },
  {
    id: "punctuation",
    mandarin: "中文逗号可以连接完整句",
    transfer: "comma splice；问句漏问号",
    wrong: "I was late, I missed the bus.",
    right: "I was late because I missed the bus.",
    weeks: "SEC writing",
    exam: "AEIS composition",
  },
];
